### PR TITLE
fix: include network dropdown on failures within App.tsx

### LINKED ISSUE #138: network chooser disappears on error
## Describe the bug

When a request to the default network fails, the UI gets wiped out:

Screenshot 2023-06-06 at 10 22 15 AM

## To Reproduce

1. Open https://bafybeiermnqk6hi7tykj6m4ccfgukdpin57i5odwu5g3r3icqwxs4rcuw4.ipfs.cf-ipfs.com
2. See error

## Expected behavior

If it fails to connect to the default network, there's still a way to choose a different network

### PR DESCRIPTION
**Pull request by iomekam**
Fixes #138

### CODE REVIEW

File: src/App.tsx [hunk 1]
```diff
@@ -25,6 +25,8 @@ import { makeAgoricChainStorageWatcher } from '@agoric/rpc';
 
 import 'react-toastify/dist/ReactToastify.css';
 import 'styles/globals.css';
+import React from 'react';
```
Comment (samsiegart) [inline src/App.tsx:28]: Can we import `lazy` on line 1 instead of two `import ... from 'react'` lines?

File: src/App.tsx [hunk 2]
```diff
@@ -142,6 +156,10 @@ const App = () => {
       <div className="w-screen max-w-7xl m-auto">
         {error ? (
           <>
+            <div className="flex justify-end flex-row space-x-2 items-center mr-6 m-2">
+              {networkDropdown}
+              <ConnectWalletButton />
```
Comment (samsiegart) [inline src/App.tsx:161]: We can remove this. There's no reason to connect the wallet at this point.

**Review by samsiegart — CHANGES_REQUESTED** [review]
Seemed to work for me! Just a couple small requests before this is ready to merge.

File: src/App.tsx [hunk 3]
```diff
@@ -1,10 +1,10 @@
-import { useState } from 'react';
+import { Suspense, useState } from 'react';
 import OfferSignerBridge from 'components/OfferSignerBridge';
 import { ToastContainer } from 'react-toastify';
 import { RouterProvider, createHashRouter } from 'react-router-dom';
 import Vaults from 'views/Vaults';
 import ErrorPage from 'views/ErrorPage';
-import { useEffect } from 'react';
+import { useEffect, lazy } from 'react';
```
Comment (samsiegart) [inline src/App.tsx:7]: Can these not be imported in the same line as `Suspense` and `useState`?

**Review by samsiegart — APPROVED** [review]
